### ISSUE TITLE
Allow passing backend credentials using the ENV variables and env file

### ISSUE THREAD

**Issue by rehanone** [cupcakearmy/autorestic#119]
I am trying to write a puppet module to automate deployment/configuration of autorestic on my cloud vms.

https://github.com/rehanone/puppet-autorestic

 I was under the impression that I would be able to pass the S3 credentials using this new env files feature in 1.3.0. However, I looks like I can only pass RESTIC_PASSWORD variable using the AUTORESTIC_<BACKEND>_KEY feature.

It would be really helpful if there was a way to pass all ENV variables using the env file like:
- AWS_ACCESS_KEY_ID
- AWS_SECRET_ACCESS_KEY

Thanks

**Comment by cupcakearmy** [comment]
That was definetely an oversign on my side, will add definetely add them!
