### ISSUE TITLE
Upgrade silently fails (no error message) if user doesn't have write permission for target

### ISSUE THREAD

**Issue by monkeyhybrid** [cupcakearmy/autorestic#120]
**Describe the bug**
Running `autorestic upgrade` silently fails when run by a user without write permission for `/usr/local/bin/autorestic`.

For example, on my machine, `/usr/local/bin/autorestic` is owned and only writeable by root. If I run `autorestic upgrade` as an ordinary user, I get the following output and exit code `0`:

```
$ autorestic upgrade
restic already installed
writing restic to /usr/local/bin/restic
find latest release of restic at GitHub
restic is up to date

Downloading: https://github.com/cupcakearmy/autorestic/releases/download/v1.3.0/autorestic_1.3.0_linux_amd64.bz2

$ echo $?
0
```

There's no error message to indicate the upgrade failed and the `0` exit code gives the false impression it completed successfully.

The autorestic download also remains in `/tmp`, one for each failed attempt.

**Expected behavior**
Output an appropriate message to `stderr` and return a non-`0` exit code. Maybe cleanup the download in `/tmp` too?

**Environment**
 - OS: Ubuntu
 - Version: 21.04

**Comment by cupcakearmy** [comment]
Thats bad, will insert some checks! Thanks
