### ISSUE TITLE
autorestic as a Docker image

### ISSUE THREAD

**Issue by haneef95** [cupcakearmy/autorestic#129]
This looks promising for what I need. Would be good for it to be made available as a docker image with a `docker-compose.yml` with the appropriate volume mounts and configs.

Could this be made available please?

Thanks,

**Comment by cupcakearmy** [comment]
Also should include rclone binaries

**Comment by haneef95** [comment]
Yup! rclone is a necessity!

However, I would prefer a modular approach, whereby, rclone is a separate container, one potential approach:
[`rclone serve restic`](https://rclone.org/commands/rclone_serve_restic/)

Not sure how much of a performance impact it'll have.

Thoughts?

**Comment by cupcakearmy** [comment]
I would only do one image, alpine based, with rclone binary preinstalled. Will not make a huge size difference

**Comment by haneef95** [comment]
Amazing! Very quick turn around! 😄
