### ISSUE TITLE
Give better feedback when backing up a repository that is not been set up yet

### ISSUE THREAD

**Issue by carlos-sarmiento** [cupcakearmy/autorestic#138]
**Describe the bug**
I'm testing out autorestic and trying to create a simple configuration to test if everything is working correctly. I'm hitting a snag in which the backup command generated by autorestic does not include the backup destination and so it ends up failing.

## config file (called `generated-config`)
```
version: 2
locations:
  test_origin:
    from: /nas-main-vol/backup-config/autorestic/test/origin/
    to:
      - test_dest
backends:
  test_dest:
    type: local
    path: /nas-main-vol/backup-config/autorestic/test/dest
    key: 'secret123'
```
## Command and output (binaries as well as paths have the right permissions set `chmod u=rwx`)
```
/nas-main-vol/backup-config/autorestic/bin/autorestic -c /nas-main-vol/backup-config/autorestic/generated-config.yml --restic-bin /nas-main-vol/backup-config/autorestic/bin/restic --ci -v backup -a
Using config:    /nas-main-vol/backup-config/autorestic/generated-config.yml


    Backing up location "test_origin"    

Backend: test_dest
> Executing: /nas-main-vol/backup-config/autorestic/bin/restic backup --tag ar:location:test_origin /nas-main-vol/backup-config/autorestic/test/origin/
exit status 1
Error: 1 errors were found
```

**Expected behavior**
Expected the local backup to succeed

**Environment**
 - OS: Raspberry PI
 - Version: autorestic 1.5.0

**Additional context**
Downgraded to 1.4.1 and removed the "version: 2" line from the config and got a descriptive error indicating the repo didn't exist. Created it with restic and reran backup using 1.4.1 and everything worked successfully. Retried with 1.5.0 and backup worked correctly. For some reason in 1.5 there is no message indicating the repo is not created

**Comment by cupcakearmy** [comment]
Oh I see, from 1.5 on restic does not check the repo at startup, for performance reasons. It should give a better failing reason, thanks for reporting!
I'll take the liberty to rename the issue :)
