### ISSUE TITLE
Running a backup with an invalid exclude file will silently fail

### ISSUE THREAD

**Issue by mamoit** [cupcakearmy/autorestic#14]
I ran into this issue after configuring an exclude file with:
```
exclude-file: ~/.autorestic.exclude
```
It didn't expand the `~/` and failed, while showing a success in the result.
Solved it by specifying the full path.

**Comment by cupcakearmy** [comment]
Thanks for finding that. Will look into it :)

**Comment by cupcakearmy** [comment]
Can reproduce & confirm

**Comment by cupcakearmy** [comment]
Fixed in latest release :)

https://github.com/cupcakearmy/autorestic/releases/tag/0.11

```
autorestic update
```
