### ISSUE TITLE
Autorestic always uses the latest docker image that does not match the binary version

### ISSUE THREAD

**Issue by beatbrot** [cupcakearmy/autorestic#140]
**Describe the bug**

Since v.1.5.1 autorestic always uses the latest `cupcakearmy/autorestic` docker image. This image, however, might not fit to the autorestic binary.

See:

https://github.com/cupcakearmy/autorestic/blob/0c71bea93ee92a2cc474de9252abf07f8b573159/internal/backend.go#L203

**Expected behavior**
By default, autorestic shall specify a docekr tag that matches the binary version. For development/debug purposes, this image tag shall be overridable.

This way, autorestic still works fine when an outdated version is used.

**Comment by cupcakearmy** [comment]
You are perfectly right, should definetely match the version and not latest, thanks for reporting!
