### ISSUE TITLE
add hooks for code 2 and 3 

### ISSUE THREAD

**Issue by jontyms** [cupcakearmy/autorestic#142]
**Is your feature request related to a problem? Please describe.**

restic backup has three error [codes](https://restic.readthedocs.io/en/latest/040_backup.html?highlight=permission#exit-status-codes).  Codes 1 and 3 indicate an error. Error code 3 means a snapshot was created but not all data was included. Error code 1 means fatal error no snapshot was created. Currently both 1 and 3 cause the failure hooks to run.
**Describe the solution you'd like**

I would like a code 1 and code 3 hook.

 This comes from https://github.com/cupcakearmy/autorestic/discussions/134

**Comment by cupcakearmy** [comment]
@jontyms would be an ENV variable good?
Something like `AUTORESTIC_ERROR_CODE` Also according to the docs you linked there is only exit code 0, 1 (normal error) and 3

**Comment by jontyms** [comment]
Sorry I missed that I updated the post. So with the env variable I could just do shell scripting magic to run different commands for each error code.
That would be fine!

**Comment by cupcakearmy** [comment]
Will add the env variable then :)
I think it's less confusing than having different hooks.

**Comment by cupcakearmy** [comment]
Will be called `$AUTORESTIC_EXIT_CODE`

**Comment by derphilipp** [comment]
To reopen up that topic:

If we have multiple backends - but have a singular hook at the end - how could we react to it "if only error 3 occured" etc?
This way we could warn "oh, not every file was saved, but the backup ran" vs "the backup did not run at all"

I would suggest something  aroudn this logic:

```
hooks:
  success: # runs upon success
  failure: # runs upon ANY failure
  warning: # runs if in ANY of the runs an error 3 occurs, but no other error
  error: # runs if ANY of the runs an error 1 occurs, no matter what other things occur
```

I would be happy to script something myself, but having the 'one place for the solution' with autorestic would be amazing;
