### ISSUE TITLE
--lean flag should omit "Using config/Using lock"

### ISSUE THREAD

**Issue by nateify** [cupcakearmy/autorestic#150]
**Is your feature request related to a problem? Please describe.**
I have a script which evaluates the output of `autorestic cron --lean` and in <1.5.0 autorestic would not print anything to stdout which I was capturing for custom logging. Now If I run `autorestic cron --lean` it prints two lines for "Using config" and "Using lock" but I would prefer it to still not output anything with `--lean`

**Comment by cupcakearmy** [comment]
Yes, absolutely! My bad

**Comment by cupcakearmy** [comment]
should be fixed in 1.5.4
