### ISSUE TITLE
Custom environment variable for hooks

### ISSUE THREAD

**Issue by baurmatt** [cupcakearmy/autorestic#151]
**Is your feature request related to a problem? Please describe.**
I need to tag backups with a timestamp. Currently I do this in a Bash script as following:

```bash
export DATE=$(date +%s)
gitlab-psql -c "SELECT pg_start_backup('Backup from ${DATE}');"
lvcreate -s -n "backup-${DATE}" -l 100%FREE vg0/gitlab-data
gitlab-psql -c "SELECT pg_stop_backup();"
```

**Describe the solution you'd like**
?

**Comment by cupcakearmy** [comment]
I'm not quite sure what you want to achieve, could you elaborate a bit more?

**Comment by baurmatt** [comment]
Sorry, this was a missunderstanding. I should've questioned the script before trying to migrate 1:1. This can be safely done without the DATE variable.

**Comment by cupcakearmy** [comment]
No worries :) happy you found a solution!
