### ISSUE TITLE
autorestic behavior change in 1.5.2 release

### ISSUE THREAD

**Issue by chenrui333** [cupcakearmy/autorestic#159]
👋  trying to update the homebrew formula to use 1.5.2 release, but found some issue with it, notably the `completion` command requires configuration file present.

```
  Error: Failure while executing; `/opt/homebrew/Cellar/autorestic/1.5.2/bin/autorestic completion bash` exited with 1. Here's the output:
  cannot find configuration file '.autorestic.yml' or '.autorestic.yaml' in config paths: ['.', 'autorestic']
```

relates to Homebrew/homebrew-core#95048

**Comment by chenrui333** [comment]
Thanks @cupcakearmy, let me give the new release a shot.

**Comment by cupcakearmy** [comment]
Actually just released a new version, might not be the last today. Maybe wait until tomorrow xD @chenrui333 
And thanks for the help on brew!
