### ISSUE TITLE
Backup with stale lock will silently fail

### ISSUE THREAD

**Issue by mamoit** [cupcakearmy/autorestic#16]
I interrupted a prune, which left a stale lock in a repo.
Then running a backup afterwards will yield a pretty fast success, even though it failed.
After running an `unlock`, it worked and created a snapshot.

EDIT: the hanging lock was caused by an interrupted backup

**Comment by cupcakearmy** [comment]
Thanks for finding that!

In the next version it should tell the user if there was an error at least.
If it's locked maybe there should be a short link to the documentation on how to unlock it (it's not documented right now)

**Comment by cupcakearmy** [comment]
For now I've added a small entry in the README
https://github.com/cupcakearmy/autorestic/blob/master/README.md#unlock-a-locked-repository

**Comment by cupcakearmy** [comment]
I was able to reproduce it 👌

**Comment by cupcakearmy** [comment]
v0.13 will show you the error. You can update with `autorestic update` :)
