### ISSUE TITLE
 exec: "bash": executable file not found in $PATH

### ISSUE THREAD

**Issue by fariszr** [cupcakearmy/autorestic#166]
**Describe the bug**
when using Hooks, autorestic uses bash to execute Hooks.

Since the Docker image uses Alpine, which doesn't include bash by default, hooks fail with:
```
exec: "bash": executable file not found in $PATH
```

**Expected behavior**

hooks should just work

**Environment**
 - OS: Fedora 35
 - Version: Docker image latest

**Additional context**
This could be fixed by including bash with the docker image.

**Comment by cupcakearmy** [comment]
Yup, good catch

**Comment by fariszr** [comment]
i created a PR to fix this, by just adding bash
