### ISSUE TITLE
[Feature Request] Support for SFTP

### ISSUE THREAD

**Issue by mamoit** [cupcakearmy/autorestic#17]
Restic supports [sftp](https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#sftp).
It would be nice to have support for it in autorestic too.

**Comment by mamoit** [comment]
Hum... it's already referenced [here](https://github.com/cupcakearmy/autorestic/blob/fa89d2941f154a3d6c8e10927c8bb66d09e7dd65/src/backend.ts#L20)...

**Comment by mamoit** [comment]
Nope... Tried to run `check` on it and...
```
$ autorestic check -b nas

Configuring Backends
nas : Configuring... ⏳Unsupported backend type: "sftp"
```
And it just hangs.

**Comment by cupcakearmy** [comment]
I'll see what I can do :) give me a few days or so :) any pr is welocomed of course xD

**Comment by cupcakearmy** [comment]
Btw. sry for the late replies, I never get notifications about new issues :/

**Comment by cupcakearmy** [comment]
@mamoit Fixed in v.014 ;)

```
 autorestic update
```

Can you confirm it works? If so feel free to close the issue.
Sry for the late reply, have turned on the notifications now, somehow I was not watching my own repo 🙈

**Comment by cupcakearmy** [comment]
I've added a example for the config in the readme https://github.com/cupcakearmy/autorestic/blob/master/README.md#example-sftp

Also now it does not get stuck if a type is not supported :)

**Comment by mamoit** [comment]
o.O that was fast!
I was about to write that you are not in a timeline here...
I should really learn typescript...

**Comment by cupcakearmy** [comment]
Well you know.. I often rant about how people don't maintain their own repos so I want to be a good example I guess 🙈
And of course it's always cool to get feedback! More people test it -> Less errors :)
Typescript is awesome yes! and since parcel is around the tooling is zero conf. Still remember the webpack days.. That was not a good experience.

**Comment by mamoit** [comment]
Tested, and works like a charm :+1:
Thank you very much!
