### ISSUE TITLE
No help command

### ISSUE THREAD

**Issue by mamoit** [cupcakearmy/autorestic#18]
The following command should print out the help:
```
autorestic help
```

**Comment by cupcakearmy** [comment]
Fair point. I can add it

**Comment by cupcakearmy** [comment]
although `--help` existst. But if it's more intuitive I can add it

**Comment by mamoit** [comment]
What I meant was that, in the help itself, given by `autorestic` without any extra arguments, one of the commands presented is `help`, as is `backup` or `exec`, hence my comment of it not being available as `autorestic help`.

**Comment by cupcakearmy** [comment]
Ohhh yes, you are absolutely right. I fixed it in v0.14 :)
Thanks for finding that!
