### ISSUE TITLE
Assets for 1.6.1 are named for 1.6.0

### ISSUE THREAD

**Issue by RetroactiveTypo** [cupcakearmy/autorestic#181]
**Describe the bug**
With the latest release of autorestic (1.16.1), the filenames are named for the 1.6.0 release instead. Breaks a few automated latest release grabbers.
**Expected behavior**
Expected `autorestic_1.6.1_linux_arm64.bz2`, got `autorestic_1.6.0_linux_arm64.bz2`
**Environment**
N/A

**Comment by cupcakearmy** [comment]
I forgot, thanks!
