### ISSUE TITLE
[Feature Request] Checksum and signatures on releases

### ISSUE THREAD

**Issue by jacobblock** [cupcakearmy/autorestic#19]
It would be great to have checksums and signing of releases going forward. https://github.com/restic/restic/releases for example provides this. https://gist.github.com/cyphar/21a1b213901a0a0ec19764ac03646ebe

Cheers!

**Comment by cupcakearmy** [comment]
Yes! that would be a nice thing! I'll check that

**Comment by cupcakearmy** [comment]
This looks like a nice way to do that http://plugins.drone.io/drone-plugins/drone-github-release/

**Comment by cupcakearmy** [comment]
@jacobblock is there a prefered checksum? i would go for sha512.

available are:
- md5
- sha1
- sha256
- sha512
- adler32
- crc32

**Comment by cupcakearmy** [comment]
Check this release https://github.com/cupcakearmy/autorestic/releases/tag/0.15

**Comment by jacobblock** [comment]
LGTM, thanks!

**Comment by cupcakearmy** [comment]
Awesome! If you have any problems feel free to reopen :)
