### ISSUE TITLE
Allow to backup single files

### ISSUE THREAD

**Issue by mutlusun** [cupcakearmy/autorestic#193]
Hello,

Thanks for all your work on autorestic! Having found this after using my own wrappers for some time and it makes life a lot easier ;)

I use restic to backup my home directory but also to backup a single config file in `/etc`. If I try this with autorestic, I receive the following error:

```
"/etc/rc.local" is not valid directory for location "home"
```

Would it be possible to allow autorestic to also backup single files? This is not an issue with restic. That would be awesome! 

Having no experience with go, I'm unfortunately not able to provide a pull request.

**Comment by xxxsen** [comment]
met the same issue

**Comment by cupcakearmy** [comment]
Absolutely. I thinks the folder error comes from autorestic checking if the directory is accessible, but also should support files. Thanks for reporting
