### ISSUE TITLE
Commented lines in the config file are gone after one run

### ISSUE THREAD

**Issue by mamoit** [cupcakearmy/autorestic#20]
If you decide to comment out a couple of lines (like a backend), it is gone when you start running a normal backup run.
Ask me how I know this. Thankfully there were backups :)

**Comment by cupcakearmy** [comment]
Yes, this is due of the library saving the secret key if it's not set. Basically it read the object and writes it back. I need to find a solution for that.

**Comment by cupcakearmy** [comment]
I should write in the docs

**Comment by cupcakearmy** [comment]
I have added it in the notes. I have an idea on how to fix it. Basically i need to overwrite the yaml to generate the encryption keys and save them. This of course is a one time operation, so I will simply prompt the user if it's ok to overwrite the yaml file and don't touch it otherwise

**Comment by cupcakearmy** [comment]
I will look at this this evening (europe time)

**Comment by cupcakearmy** [comment]
So sry for the late reply. It is fixed in the latest version (0.16).
`autorestic update`

If there is a need to overwrite the config file, you will get a copy of your old config file and be notified about it :) Keeping the comments unfortunately is practically impossible.
