### ISSUE TITLE
Allow finding large files and removing them from existing snapshots.

### ISSUE THREAD

**Issue by ibash** [cupcakearmy/autorestic#200]
**Is your feature request related to a problem? Please describe.**
I don't use autorestic right now, but restic with my own scripts. I'm planning on switching over when I find the time. Something I've found very useful is to be able to automatically find large files and then use [restic rewrite](https://github.com/restic/restic/pull/3621) command to remove them from my backups. 

**Describe the solution you'd like**
Currently this is my workflow:
1. For each snapshot run `restic ls --json -l ${snapshotId}` and write it to a file
2. I do some light processing to produce sizes of directories
3. Then sort by the largest files and directories
4. At this point I manually look through for directories / files that are large and I didn't want to backup anyway. I add them to a list of files to clean.
5. Then run `restic rewrite all --dry-run --exclude-file clean-excludes.txt --verbose=3` to spot check
6. Then run `restic rewrite all --exclude-file clean-excludes.txt --verbose=3 --forget` to remove them

This _does_ require relying on a fork of restic, but I find this very useful for my backups. Would love if something like this was available in autorestic (maybe opt-in?).

**Comment by cupcakearmy** [comment]
I think this is a bit of a niece case for an actual implementation on autorestic side.
However: you can run any restic command with `autorestic` with the [`exec`](https://autorestic.vercel.app/cli/exec) command. This should enable your workflow

**Comment by ibash** [comment]
Agree, it's probably too niche!
