### ISSUE TITLE
restic not found

### ISSUE THREAD

**Issue by jin-park-dev** [cupcakearmy/autorestic#22]
First thanks for creating fantastic wrapper. I keep searching every year for better way to setup restic (usually with ansible) and this is amazing! I hope this is the end of my search.

I followed instruction but found it couldn't backup to anything including local.
I been stuck for few hours with rather esoteric error "length null" or something along that line and backup not happening.
"autorestic check -a" showed error.
If I try backup via exec cli, it returned null null.
 
After investigation it appears restic was not installed. After manually installing restic, autorestic works!
My system is Debian Buster, zsh.
I suspect restic wasn't either installed or path wasn't correct for distro/shell.

On "https://cupcakearmy.github.io/autorestic/cli/update" - "Updates both restic and autorestic automagically." so I'm guessing under right condition restic will get installed.

**Comment by cupcakearmy** [comment]
Thanks for the feedback!

Ok this is strange but I need to fix it of course :) In theory autorestic checks if restic is available as a command and if not will tell you and terminate (correctly 😅)

However I just tried to uninstall restic and I get the same error. So I broke something. Thanks for reporting!

**Comment by cupcakearmy** [comment]
@jin-park-dev So I've fixed the problem. You can update to version 0.19 by running `autorestic update`. 
I'll close it, but feel free to reopen if I've missed something 🙂

Thanks for reporting! ...and sry for the last buggy release.
