### ISSUE TITLE
Automatically forget after backup for copies

### ISSUE THREAD

**Issue by slangdaddy** [cupcakearmy/autorestic#221]
**Is your feature request related to a problem? Please describe.**
Not sure if the issue is a problem or a feature request.

**Describe the solution you'd like**
I have configured autorestic to create a copy of a local backup to a remote location, which is working fine. I also configured the location to have "forget: prune" set (like [here](https://autorestic.vercel.app/location/forget)). Now if I run the backup using "autorestic backup -av", it tells me that it creates the backup and copies local -> remote. It also executes 'Forgetting for location "myapp"' and 'For backend "local"'. What it doesn't do is running forget for backend remote. I'd like to have autorestic run forget also for backends that are configured in a location via copy. Based on the example [here](https://autorestic.vercel.app/location/copy), that would mean running forget for "c" automatically.

**Comment by rdelaage** [comment]
I agree with you, forget policy should also be applied on copy backend

**Comment by cupcakearmy** [comment]
Absolutely agree. Hope I can add this soon

**Comment by rdelaage** [comment]
This should be fixed in my last PR

**Comment by cupcakearmy** [comment]
Thanks!

**Comment by slangdaddy** [comment]
Sorry for digging this out, but I can't quite figure out how to make use of the change. I updated to autorestic 1.7.3, but the output of  autorestic still only shows that it runs forget for the "to" location. Here's a snippet of my configuration:

`
global:
  all:
    cache-dir: /cache
  forget:
    keep-daily: 14

locations:
  nextcloud:
    from: /source/nextcloud
    to:
      - local
    copy:
      local:
        - remote
    forget: prune
    options:
      backup:
        tag:
          - nextcloud
`

And here the relevant lines from running backup -av:

`
[...]
[2022-08-23 05:10:02]     Backing up location "nextcloud"    
[2022-08-23 05:10:02] 
[2022-08-23 05:10:02] 
[2022-08-23 05:10:02] Backend: local
[2022-08-23 05:10:02] > Executing: /usr/bin/restic --cache-dir /cache backup --tag nextcloud --tag ar:location:nextcloud /sourc
e/nextcloud
[2022-08-23 05:10:03] using parent snapshot 7ea7d04a
[2022-08-23 05:10:10] 
[2022-08-23 05:10:10] Files:           0 new,     5 changed, 33780 unmodified
[2022-08-23 05:10:10] Dirs:            0 new,     8 changed,  6191 unmodified
[2022-08-23 05:10:10] Added to the repo: 20.276 MiB
[2022-08-23 05:10:10] 
[2022-08-23 05:10:10] processed 33785 files, 10.658 GiB in 0:06
[2022-08-23 05:10:10] snapshot ea158048 saved
[2022-08-23 05:10:10] Copying local → remote
[2022-08-23 05:10:10] > Executing: /usr/bin/restic --cache-dir /cache copy ea158048
[2022-08-23 05:10:12] 
[2022-08-23 05:10:12] snapshot ea158048 of [/source/nextcloud] at 2022-08-23 03:10:03.0272039 +0000 UTC)
[2022-08-23 05:10:12]   copy started, this may take a while...
[2022-08-23 05:10:15] snapshot 885e6cdd saved
[2022-08-23 05:10:15]   Forgetting for location "nextcloud"  
[2022-08-23 05:10:15] 
[2022-08-23 05:10:15] For backend "local"
[2022-08-23 05:10:15] > Executing: /usr/bin/restic --cache-dir /cache forget --tag ar:location:nextcloud --prune --keep-daily 1
4
[2022-08-23 05:10:15] Applying Policy: keep 14 daily snapshots
[2022-08-23 05:10:15] keep 1 snapshots:
[...]
[listing of snapshots]
[...]
[2022-08-23 05:10:15] Done
[2022-08-23 05:10:15] Done
`
No mention of the backend "remote"

**Comment by rdelaage** [comment]
@slangdaddy Hey can I have your complete configuration and log output ? It works here on the master branch with this config

Configuration:
```
version: 2

global:
  forget:
    keep-hourly: 1

locations:
  nextcloud:
    from: /home/rdelaage/.ssh/config
    to:
      - local
    copy:
      local:
        - remote
    forget: "yes"

backends:
  local:
    type: local
    path: /tmp/test-repo
    key: 'test'
  remote:
    type: local
    path: /tmp/test-repo-remote
    key: 'test'
```

Log:
```
Using config paths: . /home/rdelaage autorestic
Using config: 	 /home/rdelaage/Documents/autorestic/.autorestic.yml
Using lock:	 /home/rdelaage/Documents/autorestic/.autorestic.lock.yml


    Backing up location "nextcloud"    

Backend: local
> Executing: /usr/bin/restic backup --tag ar:location:nextcloud /home/rdelaage/.ssh/config
no parent snapshot found, will read all files

Files:           1 new,     0 changed,     0 unmodified
Dirs:            3 new,     0 changed,     0 unmodified
Added to the repository: 2.574 KiB (1.499 KiB stored)

processed 1 files, 1.087 KiB in 0:00
snapshot 1d84b215 saved
Copying local → remote
> Executing: /usr/bin/restic copy 1d84b215

snapshot 1d84b215 of [/home/rdelaage/.ssh/config] at 2022-10-05 12:16:13.286189222 +0200 CEST)
  copy started, this may take a while...
[0:00] 100.00%  2 / 2 packs copied

snapshot 3182fa7d saved


  Forgetting for location "nextcloud"  

For backend "local"
> Executing: /usr/bin/restic forget --tag ar:location:nextcloud --keep-hourly 1
Applying Policy: keep 1 hourly snapshots
keep 1 snapshots:
ID        Time                 Host           Tags                   Reasons          Paths
----------------------------------------------------------------------------------------------------------------
1d84b215  2022-10-05 12:16:13  romain-tuxedo  ar:location:nextcloud  hourly snapshot  /home/rdelaage/.ssh/config
----------------------------------------------------------------------------------------------------------------
1 snapshots

For backend "remote"
> Executing: /usr/bin/restic forget --tag ar:location:nextcloud --keep-hourly 1
Applying Policy: keep 1 hourly snapshots
keep 1 snapshots:
ID        Time                 Host           Tags                   Reasons          Paths
----------------------------------------------------------------------------------------------------------------
3182fa7d  2022-10-05 12:16:13  romain-tuxedo  ar:location:nextcloud  hourly snapshot  /home/rdelaage/.ssh/config
----------------------------------------------------------------------------------------------------------------
1 snapshots

Done
Done
```

**Comment by slangdaddy** [comment]
@rdelaage I was looking at old log files from before updating autorestic. Everything is actually working fine :-) Please excuse the confusion.
