### ISSUE TITLE
Incorrect filename in Github release

### ISSUE THREAD

**Issue by peterrus** [cupcakearmy/autorestic#224]
**Describe the bug**
Hey, minor thing but in the latest release on Github: https://github.com/cupcakearmy/autorestic/releases/tag/v1.7.2 the attached files still have 1.7.1 (previous version) in their filename.

It seems the release is using a 1.7.1 tag.

**Comment by cupcakearmy** [comment]
Yes, thanks for mentioning, this is wrong!
