### ISSUE TITLE
releases for other architectures

### ISSUE THREAD

**Issue by whysthatso** [cupcakearmy/autorestic#242]
I would like to use autorestic on a mipsle based device.

would it be much of a hassle to cross-compile a bunch of additional architectures?

i've been discussing this in the restic repo, and they where able to just add these to their github workflows.

i'd be happy to help out if you can point me to the right place where the builds are happening.

reference:
https://github.com/restic/restic/issues/3191
https://github.com/restic/restic/pull/3208

**Comment by cupcakearmy** [comment]
Hey there! I'm quite sure this should be not a problem! And as i want to stay as close as possible to restic this should be added :) I'll do some quick tests and then approve the pr, thanks!
