### ISSUE TITLE
Do not encrypt

### ISSUE THREAD

**Issue by r3nor** [cupcakearmy/autorestic#251]
**Is your feature request related to a problem? Please describe.**

I would like to have unencrypted backups.

**Describe the solution you'd like**

Some kind of config for a location with `encrypt: no`.

**Comment by cupcakearmy** [comment]
this is not possible https://github.com/restic/restic/issues/1018

**Comment by r3nor** [comment]
I see. Thank you for your reply @cupcakearmy. Is it possible to provide a custom encryption secret?

**Comment by cupcakearmy** [comment]
I'm not quite sure what you mean? Your encryption key ist specified in the autorestic config file.

**Comment by r3nor** [comment]
sorry if the question is somehow silly.

I can't seem to find where the ecnryption key is specified: https://autorestic.vercel.app/config

From the **warning** message on the linked page, it seems that the key is auto-generated and added to the yaml config file automatically.

**Comment by r3nor** [comment]
Sorry just found it by generating a sample complete config with `autorestic check`. Found that the key is specified as `key` in each location.

**Comment by cupcakearmy** [comment]
Exactly :) key is the encryption password used for that location

**Comment by axelsimon** [comment]
@cupcakearmy it feels the option would be better named `encryptionKey` :)
