### ISSUE TITLE
forget does not work with s3 backend

### ISSUE THREAD

**Issue by tom2199** [cupcakearmy/autorestic#281]
**Describe the bug**
I use storj as a backend, but the forget option does not work for this backend, for local it works fine. I have delete permissions with the credentials I tested this myself.

**Environment**
 - Docker

Command: autorestic forget --dry-run -v -a
Output:
```
Using config paths: . /root autorestic
Using config: 	 /autorestic/.autorestic.yaml
Using lock:	 /autorestic/.autorestic.lock.yml
  Forgetting for location "xxxx"  
For backend "storj"
> Executing: /usr/bin/restic forget --tag ar:location:xxxx --dry-run --keep-last 25
Error: exit status 1
```

**Comment by FunctionDJ** [comment]
@tom2199 Do you remember what the issue was? I'm using an SFTP backend but i have the same symptom.
