### ISSUE TITLE
1.7.5 release artifacts are incorrectly named autorestic_1.7.4_*

### ISSUE THREAD

**Issue by sumnerboy12** [cupcakearmy/autorestic#285]
**Describe the bug**
The release artifacts are named incorrectly for v1.7.5.

**Expected behavior**
Release artifacts should be named `autorestic_1.7.5_*`

**Environment**
 - OS: Docker
 - Version: 1.7.5

**Additional context**

**Comment by cupcakearmy** [comment]
Yes, my bad, really need to automate that. Thanks for reporting!

**Comment by sumnerboy12** [comment]
Hmmm - can't see any artifacts now :(

**Comment by cupcakearmy** [comment]
The build was still running, now they are there :)

**Comment by cupcakearmy** [comment]
https://github.com/cupcakearmy/autorestic/actions/runs/3956751656
