### ISSUE TITLE
Can't run tests

### ISSUE THREAD

**Issue by solopasha** [cupcakearmy/autorestic#300]
**Describe the bug**

```bash
❯ go test ./cmd/
# github.com/cupcakearmy/autorestic/cmd
cmd/root.go:58:4: (*github.com/fatih/color.Color).Println call has possible formatting directive %s
FAIL
```
Shouldn't there: https://github.com/cupcakearmy/autorestic/blob/78b0db50e042fdcae7004442c01901e939292394/cmd/root.go#L58 be Printf instead?

**Comment by szenti** [comment]
There are no tests in the cmd directory, it's not going to work.

You should rather run `go test ./...` in the project root directory.

**Comment by solopasha** [comment]
fixed in https://github.com/cupcakearmy/autorestic/commit/045513234faf97f890bb9689780dc041aa6e4c47
