### ISSUE TITLE
wget command from installation page does not work

### ISSUE THREAD

**Issue by VikingOfValhalla** [cupcakearmy/autorestic#308]
**Describe the bug**
All dependencies are installed (wget, bash, and bzip2)
https://autorestic.vercel.app/installation
Used link above to attempt installation of autorestic, however given errors below.
![image](https://github.com/cupcakearmy/autorestic/assets/87279761/c026ec0d-bdac-445f-aa96-7b173eda13b5)

Also, "Successful installation" echo runs every time even on fail. Should be placed in if/else condition.

**Expected behavior**
Software to be installed

**Environment**
 - OS: Ubuntu Desktop & Ubuntu Server
 - Version: 22.04

**Comment by dtb6** [comment]
Hi @VikingOfValhalla! The install script requires elevated privileges, so you need to run it as sudo.

**Comment by VikingOfValhalla** [comment]
Thanks @dtb6 for the response, however I assure you that is not the case:

Please see install command with prepended sudo for elevated privileges below
![image](https://github.com/cupcakearmy/autorestic/assets/87279761/7a1c6ac7-1640-4ca3-a496-154002849f5d)

**Comment by dtb6** [comment]
`sudo wget -qO - https://raw.githubusercontent.com/cupcakearmy/autorestic/master/install.sh | bash` is running `wget` with elevated privileges, but after its piped to `bash` it will just be running the install script as your normal user. 

Try running:
```
wget -qO - https://raw.githubusercontent.com/cupcakearmy/autorestic/master/install.sh >> install.sh
sudo bash install.sh
```

**Comment by VikingOfValhalla** [comment]
Hi @dtb6 yes this works. I was already able to install by cloning the repo and running `sudo ./install.sh` manually, however my main concern was the documentation. If this is how it should be installed, maybe the documentation should be updated.
That's all.
