### ISSUE TITLE
"already runnnig" check not working since v0.23

### ISSUE THREAD

**Issue by sumnerboy12** [cupcakearmy/autorestic#34]
I think [this](https://github.com/cupcakearmy/autorestic/commit/d4b8a7223fa7deb52ce45600e409cd97facc9e71) change has broken the "already running" check since you now do this check before `init(config)` runs (see line 119 above) and therefore the config location isn't known.

This means that `readLock` and `writeLock` are using `/root/.autorestic.lock` but `unlock` (on line 132 below) is using `/etc/.autorestic.lock` (assuming running as root with config in `/etc/.autorestic.yml`).

Therefore every time autorestic runs it thinks it is already running.

**Comment by cupcakearmy** [comment]
Very very good catch!, so for me it was working since there was already a lock file by chance, but of course that was just lucky. Thanks :)

**Comment by cupcakearmy** [comment]
Should be fixed. CI is running, new release should be uploaded in the next minutes.

**Comment by cupcakearmy** [comment]
https://github.com/cupcakearmy/autorestic/releases/tag/0.26 there you go :)

**Comment by sumnerboy12** [comment]
Awesome - thanks for the quick fix!!
