### ISSUE TITLE
Keep up with restic releases

### ISSUE THREAD

**Issue by OrbitingOcelot** [cupcakearmy/autorestic#352]
During my experiments with autorestic, I found out that the bundled restic version 0.16.0 is quite old, and contains some critical bugs which can even lead to data loss.
Would it be possible to periodically refresh the container image, or maybe even rebuild it automatically on restic minor releases?
Thanks :)

**Comment by MadWalnut** [comment]
@cupcakearmy I know it has just been a few days since the release of restic 0.17.0, but could you please update the container once again? That version contains a bugfix I have been waiting for :) Thanks for your work!
