### ISSUE TITLE
[Feature Request] Support for backing up docker bind mounts

### ISSUE THREAD

**Issue by jacobblock** [cupcakearmy/autorestic#4]
One of my primary backup use cases is stopping a container, backing up the bind mounted host folders, and starting the container again. It would be awesome if autorestic had this kind of functionality for locations.

**Comment by EliotBerriot** [comment]
Maybe it could work in the form of a command to launch before/after the backup?

```yaml
locations:
  docker-postgres:
    from: /srv/docker-postgres/data
    to: storage
    run_before: docker stop postgres
    run after: docker start postgres
```

this way it isn't specific to docker, and works for other use cases?

**Comment by cupcakearmy** [comment]
This WE I'll be thinking about some potential ways to backup docker volumes. I assume you mean volumes that are not mapped to the local file system :)

Good suggestion!

**Comment by jacobblock** [comment]
@EliotBerriot your proposed hook looks great for CLI support; docker, kubectl, service, systemctl, etc. would have basic support with this.

Just as an FYI you may want to reference similar functionality in other provisioning apps, e.g. https://github.com/ansible/ansible-modules-core/blob/devel/system/service.py to avoid common pitfalls with sleep/timeouts/status codes/etc.

**Comment by cupcakearmy** [comment]
It makes the tool way more flexible.  I'll implement it as soon as I have time :)

**Comment by cupcakearmy** [comment]
https://github.com/cupcakearmy/autorestic#before--after-hooks

**Comment by cupcakearmy** [comment]
```sh
# Backup
docker run --rm --volume cockpit_data:/data -v $(pwd):/backup alpine tar cf /backup/backup.tar -C /data .

# Restore
docker run --rm --volume cockpit_data:/data -v $(pwd):/backup alpine tar xf /backup/backup.tar -C /data
```

This could be the way to go

**Comment by cupcakearmy** [comment]
So, I tried a few things

### 1

```
Mount the volume -> copy data to host -> run restic
```

This worked but it had the problem that docker will modify permissions and groups of the files -> no,no
(Tried with `cp -aT` to preserve permissions)

### 2

Then i tried to do the same thing bypassing the mounted volume permissions limitation with tar

```
Mount volume -> tar -> copy tar to host -> untar in host -> run restic
```

This unfortunately did work but again the permissions were lost. My guess is that if tar does not find the user when decompressing it will replace it. Not sure..

### 3

```
Mount volume -> tar -> copy tar to host -> run restic
```

This approach works perfectly **but it does not allow incremental updates** as restic just sees the tarbal. It's not the best thing, but at least it guarantees that permissions are preserved 100%

So I implemented version 3. Will be released soon :)

**Comment by cupcakearmy** [comment]
It's done 🚀 docker volumes can now be backed up and restored with out needing them to be mounted to the host.

https://github.com/cupcakearmy/autorestic/blob/master/README.md#-docker-volumes

**Comment by fariszr** [comment]
can i backup mounted volumes using autorestic in docker ?
for example, i have autorestic running in docker.
and the container is postgres running in /home/user/postgres.
i mount /home/user/postgres to autorestic, and then it stops the container temporarily while the backup is running.

is this possible ? or does it need autorestic running outside of docker to execute commands to to stop/start the container ?

thanks for the awesome project @cupcakearmy !

**Comment by agateblue** [comment]
@fariszr you can do that exactly with the `before` and `after` hooks:

```yaml
locations:
  mydb-backup:
    from:  /home/user/postgres
    hooks:
      before:
        - sudo docker stop my-db
      after:
        - sudo docker start my-db
```

**Comment by fariszr** [comment]
The commands wouldn't work if autorestic is also running inside docker.

-------- Original Message --------

**Comment by fariszr** [comment]
The commands wouldn't work if autorestic is also running in docker.

-------- Original Message --------
