### ISSUE TITLE
Install autorestic fails when using pipefail

### ISSUE THREAD

**Issue by adsanz** [cupcakearmy/autorestic#40]
**Is your feature request related to a problem? Please describe.**

I have my own ansible role to install autrestic, and I have an issue when I set "set -o pipefail", it fails because the last line on the install script is "autorestic" and it results on 1 out code which causes this tasks to fail

**Describe the solution you'd like**

change autorestic to autorestic help to avoid 1 out code when installing

**Comment by adsanz** [comment]
I'm not sure if de 1 out code is caused by using autorestic on the script, or not having a config file, if the config file is the issue I can solve it

**Comment by adsanz** [comment]
nope, it's not the problem

**Comment by cupcakearmy** [comment]
@adsanz yes, you are right. My bad, I changed the cli framework, which rightfully now returns 1 as exit code. should work now :) feel free to test it out and close te issue if it does :)

**Comment by adsanz** [comment]
Yes! It seems solved now :D closing request
