### ISSUE TITLE
Autorestic forget fails after exit status 11

### ISSUE THREAD

**Issue by fliespl** [cupcakearmy/autorestic#417]
**Describe the bug**
Forget command fails after successful backup.

**Expected behavior**
Not fail :)

**Environment**
Ubuntu 24.04.1 LTS

# restic version
restic 0.17.3 compiled with go1.23.3 on linux/amd64
# autorestic --version
autorestic version 1.8.3

**Additional context**

```
# autorestic -c /root/.autorestic.yml --ci backup -a -vvv
Using config: 	 /root/.autorestic.yml
Using env:	 /root/.autorestic.env
Using lock:	 /root/.autorestic.lock.yml


    Backing up location "nas"    

Backend: htz
> Executing: /usr/local/bin/restic backup --tag ar:location:nas /nas/icloud
using parent snapshot 66cba6d0

Files:           0 new,     0 changed, 122361 unmodified
Dirs:            0 new,     0 changed,  2907 unmodified
Added to the repository: 0 B   (0 B   stored)

processed 122361 files, 2.007 TiB in 0:05
snapshot 31aee274 saved

Running hooks
> echo "Restic backup - OK" | /usr/bin/mailx -s "[Home NAS] Restic backup success" xxx@gmail.com
> Executing: /usr/bin/bash -c echo "Restic backup - OK" | /usr/bin/mailx -s "[Home NAS] Restic backup success" xxx@gmail.com



  Forgetting for location "nas"  

For backend "htz"
> Executing: /usr/local/bin/restic forget --tag ar:location:nas --prune --keep-last 5 --keep-monthly 12 --keep-within 14d --keep-daily 4 --keep-yearly 5 --keep-weekly 1
repo already locked, waiting up to 0s for the lock
exit status 11

Error: 1 errors were found
```

**Comment by fliespl** [comment]
Fixed by running:

```
autorestic exec -av -- unlock
```

I was testing autorestic unlock and it didn't work (probably used for local lock only).

**Comment by LM1LC3N7** [comment]
Hi,

I have the same issue resulting in Autorestic never forgeting snapshots. Yes the manual unlock method is working, but autorestic should automatically forget after backups, according to the documentation (and my config).
Instead I have this error every time.

Is there a known bug or am I the only one? If yes, how can I help investigate the issue?
(If needed I can open a new issue, but this one is exactly the same)

Thanks
