### ISSUE TITLE
Restore error: Error: target 'path' is not empty

### ISSUE THREAD

**Issue by FuzzyMistborn** [cupcakearmy/autorestic#47]
**Describe the bug**

Running some tests and trying to do a restore where I delete a single file in the folder and attempt a restore.  When I run `autorestic restore -l LOCATION --from BACKEND --to 'PATH'` I get an error of `Restore error: Error target 'PATH' is not empty` (obviously the location/backend/path are just variables here).

If I run `restic restore -r REPOSITORY latest --target 'PATH'` it works just fine.

**Expected behavior**

Should work just like the restic command restore works and ignore that there's files in the directory.

**Environment**
 - OS: [e.g. iOS] Ubuntu
 - Version: [e.g. 22] 1.03

**Additional context**

**Comment by FuzzyMistborn** [comment]
Nevermind, I see the "-f" flag now looking at the help.  Might be a good thing to document though.

**Comment by cupcakearmy** [comment]
Absolutely, forgot to mention it.
Generally it's a good idea to restore backups as a whole as files can have "dependecies" on others. This of course if we are talking about app data for a db e.g. If it's "just" some random files laying around then of course it makes sense to restore a single one :)
Thanks!
I've updated the docs https://autorestic.vercel.app/cli/restore
