### ISSUE TITLE
Ability to use custom restic binary.

### ISSUE THREAD

**Issue by cupcakearmy** [cupcakearmy/autorestic#50]
Addresses https://github.com/cupcakearmy/autorestic/issues/49#issuecomment-825677719

## Todo

- asses feasibility
- add config and flag option for custom binary
- disable auto update for custom binary

**Comment by FuzzyMistborn** [comment]
As a work around, following [this guide](https://restic.readthedocs.io/en/stable/080_examples.html#full-backup-without-root) and then running `sudo -u restic autorestic` works.

**Comment by cupcakearmy** [comment]
Yes, running restic as sudo will run all sub processes as root.
