### ISSUE TITLE
rclone backend error

### ISSUE THREAD

**Issue by n194** [cupcakearmy/autorestic#55]
**Describe the bug**
Attempting to backup to a rclone backup returns an error.
```bash
> autorestic backup -l main
Using config file: ~/.autorestic.yml
Error: backend type "rclone" is invalid
```

**Expected behavior**
I had expected it to work since [restic supports rclone](https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html#other-services-via-rclone).

**Environment**
 - OS: Linux
 - Version: 1.0.5

**Comment by cupcakearmy** [comment]
Yes, not all of the are enabled as I can't test them. I'll add it in the next version

**Comment by cupcakearmy** [comment]
Check the latest release :)

**Comment by ovizii** [comment]
> Check the latest release :)

Is there any documentation to go with the "latest release" you mentioned? 
I can't find any on how to add a rclone remote as backend. 

The only hint is here: https://github.com/cupcakearmy/autorestic/discussions/153#discussion-3821402 and I am still wondering if I guessed right: https://github.com/cupcakearmy/autorestic/discussions/153#discussioncomment-7222014
