### ISSUE TITLE
autorestic check -a fails to run

### ISSUE THREAD

**Issue by FuzzyMistborn** [cupcakearmy/autorestic#56]
**Describe the bug**

Running `autorestic check -a` results in an error "unknown shorthand flag: 'a' in -a"

**Expected behavior**

https://autorestic.vercel.app/quick#check

Runs a check as per docs

**Environment**
 - OS: [e.g. iOS] Ubuntu
 - Version: [e.g. 22] 1.0.6

**Additional context**

Log: 
```
$ autorestic check -a
Error: unknown shorthand flag: 'a' in -a
Usage:
  autorestic check [flags]

Flags:
  -h, --help   help for check

Global Flags:
      --ci              CI mode disabled interactive mode and colors and enables verbosity
  -c, --config string   config file (default is $HOME/.autorestic.yml or ./.autorestic.yml)
  -v, --verbose         verbose mode

Error: unknown shorthand flag: 'a' in -a
```

**Comment by cupcakearmy** [comment]
My bad, in the previous version there was a flag, since 1.x that has gone, I forgot to update the docs. Thanks!
