### ISSUE TITLE
Autorestic on Apple Silicon

### ISSUE THREAD

**Issue by SebDanielsson** [cupcakearmy/autorestic#57]
It would be awesome to run Autorestic on my M1 MacBook Air. Ant plans on making autorestic work on armv8?

**Comment by cupcakearmy** [comment]
Hey,
Yes! would love to. restic itself [does not have native binaries as of now](https://github.com/restic/restic/releases).
I'm quite positive that restic and autorestic however would run fine with rosetta using the normal amd64 version.
Probably you tried the install script and it failed as the native version does not recognize the new architecture.
Could you run the following commands `uname` and `uname -m` and tell me what is coming back?
Also, if you install manually install restic (from brew e.g.) and autorestic from the release pages (the darwin one). it should work fine.

**Comment by SebDanielsson** [comment]
uname -m returns _**arm64**_ which is what Apple usually call binaries for their Apple Silicon chips. My odroid-n2 running Manjaro ARM returns _**aarch64**_.

**Comment by cupcakearmy** [comment]
Ok perfect, so it's the usual `arm64`, awesome. Restic itself has no binaries for it though yet. I've added arm build for darwin and updated the install script. Could you confirm that it works?

**Comment by SebDanielsson** [comment]
Making progress! :)

Just tested the install script on my MacBook and found two bugs. The script outputs "Successfully installed autorestic" even though autorestic doesn't get installed to /usr/local/bin. Maybe add a condition that the file needs to be there before printing it?

Also, got permission errors and the program didn't get installed. See the output below:
```
➜ sudo curl -s https://raw.githubusercontent.com/CupCakeArmy/autorestic/master/install.sh | bash
darwin
arm64
/usr/local/bin/autorestic.bz2: Permission denied
bzip2: Can't open input file /usr/local/bin/autorestic.bz2: No such file or directory.
chmod: /usr/local/bin/autorestic: No such file or directory
bash: line 40: autorestic: command not found
Successfully installed autorestic
~
➜ ls /usr/local/bin/
total 0
drwxr-xr-x  16 root  wheel   512B Apr 26 14:04 .
drwxr-xr-x   7 root  wheel   224B Mar  9 21:53 ..
lrwxr-xr-x   1 root  wheel    68B Mar  7 20:15 code -> /Applications/Visual Studio Code.app/Contents/Resources/app/bin/code
lrwxr-xr-x   1 root  wheel    62B Feb 11 22:18 com.docker.cli -> /Applications/Docker.app/Contents/Resources/bin/com.docker.cli
lrwxr-xr-x   1 root  wheel    54B Feb 11 22:18 docker -> /Applications/Docker.app/Contents/Resources/bin/docker
lrwxr-xr-x   1 root  wheel    77B Feb 11 22:18 docker-compose -> /Applications/Docker.app/Contents/Resources/bin/docker-compose/docker-compose
lrwxr-xr-x   1 root  wheel    73B Feb 11 22:18 docker-credential-desktop -> /Applications/Docker.app/Contents/Resources/bin/docker-credential-desktop
lrwxr-xr-x   1 root  wheel    75B Feb 11 22:18 docker-credential-ecr-login -> /Applications/Docker.app/Contents/Resources/bin/docker-credential-ecr-login
lrwxr-xr-x   1 root  wheel    77B Feb 11 22:18 docker-credential-osxkeychain -> /Applications/Docker.app/Contents/Resources/bin/docker-credential-osxkeychain
lrwxr-xr-x   1 root  wheel    72B Feb 28 19:23 github -> /Applications/GitHub Desktop.app/Contents/Resources/app/static/github.sh
lrwxr-xr-x   1 root  wheel    56B Feb 11 22:18 hub-tool -> /Applications/Docker.app/Contents/Resources/bin/hub-tool
lrwxr-xr-x   1 root  wheel    67B Feb 11 22:18 hyperkit -> /Applications/Docker.app/Contents/Resources/bin/com.docker.hyperkit
lrwxr-xr-x   1 root  wheel    55B Feb 11 22:18 kubectl -> /Applications/Docker.app/Contents/Resources/bin/kubectl
lrwxr-xr-x   1 root  wheel    55B Feb 11 22:18 kubectl.docker -> /Applications/Docker.app/Contents/Resources/bin/kubectl
lrwxr-xr-x   1 root  wheel    54B Feb 11 22:18 notary -> /Applications/Docker.app/Contents/Resources/bin/notary
lrwxr-xr-x   1 root  wheel    65B Feb 11 22:18 vpnkit -> /Applications/Docker.app/Contents/Resources/bin/com.docker.vpnkit
```

**Comment by cupcakearmy** [comment]
Mhhh `/usr/local/bin` should not belonging to root. It does not in normal installations of macOS or Linux. Also the script should be run with sudo, however I wonder how it failed permissions while being run as sudo 🤔
You are right, the exit code should be 1 and should not say it's installed successfully 😅

**Comment by SebDanielsson** [comment]
Yeah the same thing happened on my odroid-n2 running Manjaro ARM. But there I could do:
```
su
curl -s https://raw.githubusercontent.com/CupCakeArmy/autorestic/master/install.sh | bash
```

and after that it installed without any problems.

Instead of using the install script on macOS, maybe offer Autorestic through Homebrew, MacPorts and the Nix package manager?

**Comment by cupcakearmy** [comment]
Yes homebrew would be a great option, I have never looked into how it works though. I'll open another ticket for brew. However if the binaries work on arm I would like to close this ticket :) let me know 🙂

**Comment by SebDanielsson** [comment]
Can confirm that both binaries is running great om my two ARM64 systems. Thanks!😃
