### ISSUE TITLE
The `exec` command does not print restic's output. 

### ISSUE THREAD

**Issue by david-boles** [cupcakearmy/autorestic#61]
**Describe the bug**
Running a command, e.g. `autorestic exec -a -- snapshots` does not print out the result:

```
Using config file: /home/deb/.autorestic.yml


    Executing on "b2"    

```

**Expected behavior**
Restic's output should be printed. For example, by adding the verbose flag, `autorestic exec -a -v -- snapshots` yields:
```
Using config file: /home/deb/.autorestic.yml
> Executing: /usr/local/bin/restic snapshots


    Executing on "b2"    

> Executing: /usr/local/bin/restic snapshots
ID        Time                 Host        Tags        Paths
--------------------------------------------------------------------------
...information about snapshots printed here...
--------------------------------------------------------------------------
n snapshots

```

**Environment**
 - OS: Debian Sid
 - Version: 1.0.6

**Additional context**
If this is intended behavior, the `exec` docs should probably have a note added to them.

**Comment by cupcakearmy** [comment]
Stupid questioin, but did you wait until the script was done?

Just tested with `-av` and single backends `-v -b foo` and it works.

<img width="669" alt="Screenshot 2021-04-27 at 08 32 58" src="https://user-images.githubusercontent.com/14948823/116196303-9e8acf80-a733-11eb-8e52-aeb4e07f4238.png">
 
Is there no other error message?

**Comment by david-boles** [comment]
Hi @cupcakearmy, glad those other PRs were helpful!

Sorry, I could have explained this a little better. It works great with the verbose flag, it just seems odd that you would need a verbose flag to see the the output of the command that you're trying to run. It definitely could be a design decision and isn't necessarily a bug, but the example in the docs doesn't include the verbose flag (just `autorestic exec -a -- snapshots`).

**Comment by cupcakearmy** [comment]
Ah I see. I was debating that with myself too, but chose to have the verbose flag not enabled by default for consistency between the commands. The docs should definetely have the `-v`, I updated the docs, thanks again :)
