### ISSUE TITLE
Flag for disabling 'Skipping %, not due yet' log lines

### ISSUE THREAD

**Issue by octfx** [cupcakearmy/autorestic#65]
When defining several cron schedules in `.autorestic.yml` and running autorestic as a con every x minutes, the log gets filled with a log of lines stating that the current location is not due for backing up yet.

In my current use case I'm appending the log output of `autorestic cron --ci` into a file which is sent by mail on a daily basis.

I'd would be nice to have some kind of flag that only outputs the acual backup process and/or errors.

**Comment by cupcakearmy** [comment]
I can add that, seems like a useful thing to have :)

**Comment by cupcakearmy** [comment]
added in v1.0.8
`autorestic upgrade` to get the lastest :)
Feel free to reopen if something should not work
