### ISSUE TITLE
autorestic 1.1.0 OSX test failure

### ISSUE THREAD

**Issue by chenrui333** [cupcakearmy/autorestic#77]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>test failure</summary>

```
==> /usr/local/Cellar/autorestic/1.1.0/bin/autorestic backup -a
Using config file: /private/tmp/autorestic-test-20210506-15136-1da7wkc/.autorestic.yml


    Backing up location "foo"

Backend: bar
Fatal: unable to open config file: Stat: stat /private/tmp/autorestic-test-20210506-15136-1da7wkc/data/config: no such file or directory
Is there a repository at the following location?
/private/tmp/autorestic-test-20210506-15136-1da7wkc/data

Done
0
Error: 1 errors were found
```

</details>

Full build log is in here, https://github.com/Homebrew/homebrew-core/runs/2519165718
relates to https://github.com/Homebrew/homebrew-core/pull/76775

**Comment by cupcakearmy** [comment]
Hey, thanks for making the brew PRs! Are they automatic?
I think it might be a temp folder thing? Looks like the tmp folder was deleted

**Comment by cupcakearmy** [comment]
@chenrui333 can I help somehow?

**Comment by chenrui333** [comment]
looks like there is a new release, let me give it a try.

**Comment by chenrui333** [comment]
Still the same issue

```
==> /usr/local/Cellar/autorestic/1.1.1/bin/autorestic backup -a
Last 15 lines from /Users/rchen/Library/Logs/Homebrew/autorestic/test.01.autorestic:
-a

Using config file: /private/tmp/autorestic-test-20210518-29613-14k32t8/.autorestic.yml


    Backing up location "foo"

Backend: bar
Fatal: unable to open config file: Stat: stat /private/tmp/autorestic-test-20210518-29613-14k32t8/data/config: no such file or directory
Is there a repository at the following location?
/private/tmp/autorestic-test-20210518-29613-14k32t8/data

Done
0
Error: 1 errors were found
Error: autorestic: failed
```

**Comment by cupcakearmy** [comment]
Thanks for trying again. Will check later today.

**Comment by cupcakearmy** [comment]
I see a new version was released to brew (https://github.com/Homebrew/homebrew-core/blob/master/Formula/autorestic.rb) so i will close the issue :) Thanks for all the work ❤️
