### ISSUE TITLE
Case change of backend with "check"

### ISSUE THREAD

**Issue by mattjmeier** [cupcakearmy/autorestic#78]
**Describe the bug**

Thanks for making autorestic! It's a great way to configure backups.

Something you might want to know - not sure if it's an edge case or what... but I ran the check command on my config, and it rewrote the file as anticipated, but it wouldn't validate because I had a capital letter in the title of a backend. It was re-written by autorestic in lower case within the backends section, but not the locations section. I had to manually change the title in the locations section.

**Expected behavior**

I would expect the case to remain unaltered.

**Environment**
 - Version: [e.g. 22]

Debian 4.19

**Additional context**

Thanks!

**Comment by cupcakearmy** [comment]
thanks for the but report! definetely should be addressed.

**Comment by cupcakearmy** [comment]
So the go yaml package makes everything lowercase :/ which makes this impossible to fix or check really :/

**Comment by mattjmeier** [comment]
Hmm did it only impact the backend section because that gets parsed but the remainder of the file doesn't? It seems like if it gets altered it would be all or nothing. 

Actually it must have parsed the whole thing because it rewrote some things without quotes too.

Anyway if it's not trivial to find a solution maybe it could at least be mentioned in the docs in case someone else has the same problem.

**Comment by cupcakearmy** [comment]
It's because the names of backends are `keys` of a map while the list of backends in the locations are values. Values get read properly but keys get lower cased. I'll add a notice in the docs and the CLI :)
