### ISSUE TITLE
[Feature request] Backup from stdin

### ISSUE THREAD

**Issue by EliotBerriot** [cupcakearmy/autorestic#8]
Sometimes, simply copying a directory isn't enough for a backup. This happens for instance when you're backing up a SQL database such as MySQL or PostgreSQL: to ensure the backup integrity, you need to use `pg_dump` and backup the output of that command.

Luckily, [restic supports backing up data piped via stdin](https://restic.readthedocs.io/en/latest/040_backup.html#reading-data-from-stdin). Do you think it would be possible to support this in `autorestic`?

What I currently have in mind is:

```
locations:
  psqldata:
    command: pg_dumpall
```

Which `autorestic` would internally translate to `pg_dumpall | restic backup --stdin --stdin-filename psqldata`.

I'm going to experiment with that, let me know what you think about it :)

**Comment by cupcakearmy** [comment]
Same with mongodump, might be usefull yes. Altouhgh at least with mongo it's not seen as the reccomended way to go about it.

**Comment by bthj** [comment]
@EliotBerriot , your [backup journey article](https://eliotberriot.com/2019/12/03/a-quest-for-backups-a-journey-through-automation.html) took me here and I'm subscribing to this issue :)

At the risk of hijacking the discussion here, I'd like to ask if you're currently using your own tool, [savior](https://github.com/EliotBerriot/savior), in conjunction with autorestic?

**Comment by cupcakearmy** [comment]
I will do some testing this WE (hopefully I don't forget xD)
might be a bit tricky piping it through node and then to restic, but we'll see.

**Comment by EliotBerriot** [comment]
> At the risk of hijacking the discussion here, I'd like to ask if you're currently using your own tool, savior, in conjunction with autorestic?

@bthj no I've completely dropped it, I've been using https://github.com/cupcakearmy/autorestic#before--after-hooks (dump in a before hook, remove the dump in the after hook, backup the dump) as a workaround until we can pipe backups directly to stdin.

> I will do some testing this WE (hopefully I don't forget xD)
> might be a bit tricky piping it through node and then to restic, but we'll see.

@cupcakearmy yeah, wy first attempts at this (back in december) got stuck at this point unfortunately: piping stdin to a subprocess launched by node.

**Comment by cupcakearmy** [comment]
As this feature is not really relevant anymore and adds significant implementation I will close this. feel free to reopen if necessary

**Comment by xpufx** [comment]
@berlincount A similar tool 'resticprofile' supports backing up from STDIN. I actually have a different problem with it regarding hooks that is not supported and hoped autorestic would fix this situation.

**Comment by mxsrm** [comment]
Any knews on the stdin support? I prefer autorestic to resticprofile in every other aspect, but that one is really nice for dumping your databases running in docker directly into your backup bucket...

**Comment by elpollodiablo** [comment]
I too was about to use autorestic until I found that using stdin isn't possible :S
