### ISSUE TITLE
Forget + Prune is not actually pruning

### ISSUE THREAD

**Issue by FuzzyMistborn** [cupcakearmy/autorestic#83]
**Describe the bug**

Running `autorestic forget -a --prune` does not actually prune the data.  Running `autorestic exec -a -- prune` does

**Expected behavior**

Maybe I'm not reading [the docs](https://autorestic.vercel.app/cli/forget) right but I thought that adding --prune with the forget command would do both a forget and a prune.  But I noticed the files weren't getting pruned though snapshots were being forgotten.

**Environment**
 - OS: Ubuntu
 - Version: 1.1.0

**Additional context**

**Comment by cupcakearmy** [comment]
`--prune` should actually remove the data yes. According to the restic docs it should work though (https://restic.readthedocs.io/en/stable/060_forget.html?highlight=prune#remove-a-single-snapshot)

If I run `autorestic -av --prune` it shows the `--prune` flag in the command passed to restic, so I'm a bit lost why it would not prune your backups, will investigate further

**Comment by cupcakearmy** [comment]
Just tried few repos but could not replicate it 🤔

**Comment by FuzzyMistborn** [comment]
Huh, that's odd.  For me it was clearing the snapshots but the size of the repos was not shrinking.  It's fine, just adding the `autorestic exec -a prune` works for me so it's just 2 commands instead of 1.
