### ISSUE TITLE
32bit Raspberry Pi support in install.sh

### ISSUE THREAD

**Issue by Vogete** [cupcakearmy/autorestic#85]
**Is your feature request related to a problem? Please describe.**
I just installed Autorestic on my Raspberry Pi 3B and 3B+ (love it by the way), but the install.sh script only accounts for 64bit ARM processors. Since there is a 32bit ARM package available from the releases, it would be nice to detect at least the major 32bit ARM architectures in the `install.sh` script.

**Describe the solution you'd like**
I downloaded the install.sh file, and added the following clause for the architecture detection statement:
```sh
elif [[ $NATIVE_ARCH == *"armv7l"* ]]; then
    ARCH=arm
```
This worked like wonders for me (because the RPI3B and 3B+ are reporting as `armv7l` in `uname`), so I thought maybe others would appreciate it too.  I can't verify this, but I believe the RPI 2 is also `armv7l`. (I think the RPI 1 is not, but again, don't quote me on that).

So it would be quite nice to add another elif clause that checks for 32 bit ARM, like the older RPI devices. The full if statement looks like this for me:

```sh
NATIVE_ARCH=$(uname -m | tr '[:upper:]' '[:lower:]')
if [[ $NATIVE_ARCH == *"x86_64"* ]]; then
    ARCH=amd64
elif [[ $NATIVE_ARCH == *"arm64"* || $NATIVE_ARCH == *"aarch64"* ]]; then
    ARCH=arm64
elif [[ $NATIVE_ARCH == *"x86"* ]]; then
    ARCH=386
elif [[ $NATIVE_ARCH == *"armv7l"* ]]; then
    ARCH=arm
else
    echo "Could not determine Architecure automatically, please check the release page manually: https://github.com/cupcakearmy/autorestic/releases"
    exit 1
fi
echo $ARCH
```

**Comment by cupcakearmy** [comment]
Sure thing :) Thanks for reporting. I'll add `armv7` instead of `armv7l as it's more general.

**Comment by cupcakearmy** [comment]
Done :) if you could try out and tell me if it worked, that'd be great :)

**Comment by Vogete** [comment]
good point on `armv7`! I just tried it, and it works like a charm! Thank you! :)

**Comment by cupcakearmy** [comment]
awesome!
