### ISSUE TITLE
Verbose output is confusing with regards to the command line being executed

### ISSUE THREAD

**Issue by g-a-c** [cupcakearmy/autorestic#92]
**Describe the bug**

When the verbose output is enabled, the `restic` command line is output to `stdout`; however the path is always represented as `.` which is really confusing as it looks like `autorestic` is not honouring your `location:`. In actual fact `autorestic` is setting the CWD for the `restic` process it spawns so that `.` _is_ correct.

**Expected behavior**

Rather than dumping just the raw command line (which is technically correct), there should be an attempt to clarify what `restic` is doing including any background trickery

**Environment**
 - OS: Linux
 - Version: 1.1.2

**Additional context**

**Comment by cupcakearmy** [comment]
Good point. You mean hooks proably? or in general. In theory one could and something like "execunting in /some/dir"

**Comment by g-a-c** [comment]
> In theory one could and something like "execunting in /some/dir"

Something as simple as that probably works. All I know is that I kept seeing it running in `.`, so I would Ctrl-C and assume I screwed up the config. Then after a few tries of that, I was brave enough to let it run, and checked `/proc/${PID}/cwd` to find that it was correct and was actually backing up what I wanted it to.

**Comment by cupcakearmy** [comment]
I've added a message, will release in the next version :)
